export const AIChannels = {
  AI_QUERY: "ai:query",
  AI_STREAM_START: "ai:stream-start",
  AI_STREAM_CHUNK: "ai:stream-chunk",
  AI_STREAM_END: "ai:stream-end",
  AI_STREAM_IDLE: "ai:stream-idle",
  AI_RESEARCH_CLARIFICATION: "ai:research-clarification",
  AUTOMATION_ACTIVITY_START: "automation:activity-start",
  AUTOMATION_ACTIVITY_CHUNK: "automation:activity-chunk",
  AUTOMATION_ACTIVITY_END: "automation:activity-end",
  AI_CANCEL: "ai:cancel",
  AI_FETCH_MODELS: "ai:fetch-models",
  AGENT_RUNTIME_GET: "agent-runtime:get",
  AGENT_RUNTIME_UPDATE: "agent-runtime:update",
  AGENT_PAUSE: "agent:pause",
  AGENT_RESUME: "agent:resume",
  AGENT_SET_APPROVAL_MODE: "agent:set-approval-mode",
  AGENT_APPROVAL_RESOLVE: "agent:approval-resolve",
  AGENT_CHECKPOINT_CREATE: "agent:checkpoint-create",
  AGENT_CHECKPOINT_RESTORE: "agent:checkpoint-restore",
  AGENT_CHECKPOINT_UPDATE_NOTE: "agent:checkpoint-update-note",
  AGENT_UNDO_LAST_ACTION: "agent:undo-last-action",
  AGENT_SESSION_CAPTURE: "agent:session-capture",
  AGENT_SESSION_RESTORE: "agent:session-restore",
} as const;
